export const REQUEST_CHARACTERS = "REQUEST_CHARACTERS";
export const RECEIVE_CHARACTERS = "RECEIVE_CHARACTERS";
export const FILTER_CHARACTERS = "FILTER_CHARACTERS";
export const CHANGE_TO_B = "CHANGE_TO_B";
export const CHANGE_TO_A = "CHANGE_TO_A";
export const RECEIVE_CHARACTERS_B = "RECEIVE_CHARACTERS_B";
